\LoadClass[12pt]{article}

\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage{centernot}
\usepackage{fontspec}
\usepackage{geometry}
\usepackage{mleftright}
\usepackage{parskip}
\usepackage{physics}
\usepackage{sidenotes}

\geometry{
	a4paper,
	margin=1.5in
}
\let\footnote\sidenote
\setmainfont{TeX Gyre Pagella}
\theoremstyle{definition}
\newtheorem{axiom}{Axiom}
\newtheorem{definition}{Definition}
\newtheorem{metadefinition}{Metadefinition}
\newtheorem{notation}{Notation}
\newtheorem{theorem}{Theorem}
\theoremstyle{remark}
\newtheorem{remark}{Remark}
\newtheorem{example}{Example}

\newcommand{\N}{\mathbb{N}}
